create schema sensor;

create table sensor.Sensor
(id int generated by default as identity primary key,
 name varchar not null unique);


create table sensor.Measurement
(id int generated by default as identity primary key,
 temperature decimal not null,
 raining boolean not null,
 measure_time	timestamp not null,
 sensor_id int not null references sensor.Sensor(id));